export const socialIconsData = [
  {
    id: 1,
    class: "fab fa-linkedin-in",
    href: "https://www.linkedin.com/company/102031252/admin/dashboard/",
  },
  {
    id: 2,
    class: "fab fa-instagram",
    href: "https://www.instagram.com/analyticshala/",
  },
];

export const menuMobileData = [
  {
    id: 0,
    class: "one",
    icon: "fas fa-home",
    name: "Home",
    href: "/",
  },
  {
    id: 1,
    class: "two",
    icon: "fas fa-user",
    name: "About Us",
    href: "/aboutUs",
  },
  {
    id: 2,
    class: "three",
    icon: "fas fa-file-code",
    name: "Courses",
    href: "/courses",
  },
  {
    id: 3,
    class: "four",
    icon: "fas fa-briefcase",
    name: "FAQ",
    href: "/#faq",
  },
  {
    id: 4,
    class: "five",
    icon: "fas fa-project-diagram",
    name: "Contact Us",
    href: "/#contact",
  },
];

export const heroMarqData = [
  { id: 1, name: "Python", img: "/assets/marq/python.svg", color: "#3776AB" },
  { id: 2, name: "SQL", img: "/assets/marq/postgresql.svg", color: "#4169E1" },
  {
    id: 3,
    name: "TensorFlow",
    img: "/assets/marq/tensorflow.svg",
    color: "#FF6F00",
  },
  { id: 4, name: "PyTorch", img: "/assets/marq/pytorch.svg", color: "#EE4C2C" },
  { id: 5, name: "Jupyter", img: "/assets/marq/jupyter.svg", color: "#F37626" },
  {
    id: 6,
    name: "Scikit-learn",
    img: "/assets/marq/sklearn.svg",
    color: "#F7931E",
  },
  {
    id: 7,
    name: "Pandas",
    img: "/assets/marq/pandas.svg",
    color: "#150458",
    darkLogo: true,
  },
  {
    id: 8,
    name: "NumPy",
    img: "/assets/marq/numpy.svg",
    color: "#4DABCF",
    darkLogo: true,
  },
  {
    id: 9,
    name: "OpenAI",
    img: "/assets/marq/openai.svg",
    color: "#10A37F",
    darkLogo: true,
  },
  {
    id: 10,
    name: "LangChain",
    img: "/assets/marq/langchain.svg",
    color: "#1C3C3C",
    darkLogo: true,
  },
  { id: 11, name: "Excel", icon: "fas fa-file-excel", color: "#217346" },
  { id: 12, name: "Power BI", icon: "fas fa-chart-pie", color: "#F2C811" },
  { id: 13, name: "Tableau", icon: "fas fa-chart-bar", color: "#E97627" },
  { id: 14, name: "ML / AI", icon: "fas fa-brain", color: "#9333EA" },
];

export const workshopData = {
  upcoming: [
    {
      id: 1001,
      slug: "excel-for-data-analysis",
      image:
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop",
      category: "Data Analytics",
      categoryColor: "#16a34a",
      level: "Beginner",
      title: "Excel for Data Analysis",
      desc: "Master formulas, pivot tables, charts, and dashboards. The fastest path from spreadsheet user to data analyst.",
      tags: ["Excel", "Pivot Tables", "Dashboards", "Data Cleaning"],
      date: "March 29, Saturday",
      time: "10:00 AM – 1:00 PM",
      duration: "3 Hours",
      eventMode: ["Online", "Offline"],
      instructor: "Faizan Ansari",
      seatsLeft: 8,
      totalSeats: 30,
      price: "₹999",
      originalPrice: "₹1,999",
      outcomes: [
        "Master 30+ essential Excel formulas used in real analyst roles",
        "Build pivot tables to summarise and analyse large datasets",
        "Create interactive dashboards with slicers and dynamic charts",
        "Clean and transform messy, real-world data efficiently",
        "Automate repetitive tasks using named ranges and dynamic arrays",
      ],
      curriculum: [
        {
          time: "10:00 – 10:45",
          title: "Excel Foundations & Formula Mastery",
          desc: "VLOOKUP, INDEX-MATCH, IF nesting, SUMIFS - formulas every analyst needs",
        },
        {
          time: "10:45 – 11:30",
          title: "Pivot Tables & Data Summarisation",
          desc: "Group, filter, and aggregate large datasets in minutes",
        },
        {
          time: "11:30 – 12:00",
          title: "Data Cleaning & Transformation",
          desc: "Remove duplicates, handle blanks, and reshape raw data",
        },
        {
          time: "12:00 – 12:45",
          title: "Interactive Dashboard Design",
          desc: "Build a live Excel dashboard with slicers, charts, and named ranges",
        },
        {
          time: "12:45 – 13:00",
          title: "Q&A & Interview Tips",
          desc: "Common Excel interview questions and how to showcase your work",
        },
      ],
      whoIsItFor: [
        "Freshers entering the job market who want an analyst-ready skill",
        "Working professionals who use Excel daily but haven't fully mastered it",
        "Anyone preparing for data or operations analyst interviews",
        "Students who want job-ready Excel experience before graduation",
      ],
    },
    {
      id: 1002,
      slug: "sql-masterclass",
      image:
        "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80&auto=format&fit=crop",
      category: "Data Analytics",
      categoryColor: "#16a34a",
      level: "Intermediate",
      title: "SQL Masterclass for Analysts",
      desc: "From SELECT to advanced window functions - become the SQL analyst every data team wants to hire.",
      tags: ["SQL", "Window Functions", "Query Optimization", "PostgreSQL"],
      date: "April 5, Saturday",
      time: "11:00 AM – 2:00 PM",
      duration: "3 Hours",
      eventMode: ["Online"],
      instructor: "Waseem Ahmad",
      seatsLeft: 12,
      totalSeats: 25,
      price: "₹1,499",
      originalPrice: "₹2,499",
      outcomes: [
        "Write complex multi-table JOINs with full confidence",
        "Use window functions - ROW_NUMBER, RANK, LAG, LEAD - like a pro",
        "Understand query execution and speed up slow, costly queries",
        "Master CTEs, subqueries, and conditional aggregations",
        "Solve the SQL problems that come up in real analyst interviews",
      ],
      curriculum: [
        {
          time: "11:00 – 11:40",
          title: "SQL Refresher & Database Setup",
          desc: "PostgreSQL environment, schema navigation, and SELECT fundamentals",
        },
        {
          time: "11:40 – 12:15",
          title: "Advanced JOINs & Set Operations",
          desc: "INNER, LEFT, FULL OUTER, CROSS JOIN, UNION vs UNION ALL",
        },
        {
          time: "12:15 – 12:45",
          title: "CTEs, Subqueries & Aggregations",
          desc: "WITH clauses, nested queries, GROUP BY, and HAVING",
        },
        {
          time: "12:45 – 13:25",
          title: "Window Functions Deep Dive",
          desc: "ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG, running totals",
        },
        {
          time: "13:25 – 14:00",
          title: "Query Optimisation & Interview Problems",
          desc: "EXPLAIN plans, indexing basics, and 10 live interview questions",
        },
      ],
      whoIsItFor: [
        "Analysts who know basic SQL but want to handle complex queries",
        "Anyone preparing for data engineer or data analyst interviews",
        "Developers who want to write faster, cleaner database queries",
        "BI professionals who want to move beyond simple report queries",
      ],
    },
    {
      id: 1003,
      slug: "power-bi-dashboard-bootcamp",
      image:
        "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
      category: "Data Visualization",
      categoryColor: "#f97316",
      level: "Intermediate",
      title: "Power BI Dashboard Bootcamp",
      desc: "Build interactive, executive-level dashboards from scratch. Learn DAX, data modelling, and visual storytelling.",
      tags: ["Power BI", "DAX", "Data Modelling", "Dashboards"],
      date: "April 12, Saturday",
      time: "10:00 AM – 1:00 PM",
      duration: "3 Hours",
      eventMode: ["Online", "Offline"],
      instructor: "Faizan Ansari",
      seatsLeft: 5,
      totalSeats: 20,
      price: "₹1,999",
      originalPrice: "₹3,499",
      outcomes: [
        "Build executive-level dashboards from raw data in Power BI",
        "Write DAX measures for KPIs, YoY growth, and rolling averages",
        "Model data with star schemas and well-structured relationships",
        "Apply visual storytelling best practices for leadership presentations",
        "Publish dashboards to Power BI Service and share with stakeholders",
      ],
      curriculum: [
        {
          time: "10:00 – 10:30",
          title: "Power BI Interface & Data Import",
          desc: "Connect to Excel, CSV, and SQL sources; navigate the Power Query editor",
        },
        {
          time: "10:30 – 11:15",
          title: "Data Modelling & Relationships",
          desc: "Star schema design, fact vs dimension tables, cardinality settings",
        },
        {
          time: "11:15 – 12:00",
          title: "DAX Formulas & Custom Measures",
          desc: "CALCULATE, FILTER, SUMX, time intelligence - build real KPIs",
        },
        {
          time: "12:00 – 12:45",
          title: "Dashboard Design & Visualisations",
          desc: "Charts, maps, slicers, bookmarks, and drill-through navigation",
        },
        {
          time: "12:45 – 13:00",
          title: "Publishing, Sharing & Q&A",
          desc: "Deploy to Power BI Service, manage permissions, and present findings",
        },
      ],
      whoIsItFor: [
        "Business analysts and report developers moving beyond Excel",
        "Managers who want to build their own self-service dashboards",
        "Excel power users ready to step up to enterprise BI tools",
        "Anyone in a data-heavy role who reports to leadership regularly",
      ],
    },
    {
      id: 1004,
      slug: "python-for-data-science",
      image:
        "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
      category: "Data Science & AI",
      categoryColor: "#0d9488",
      level: "Intermediate",
      title: "Python for Data Science",
      desc: "pandas, NumPy, Matplotlib, and Seaborn - learn the entire Python data stack in one intensive day.",
      tags: ["Python", "Pandas", "NumPy", "Matplotlib"],
      date: "April 19, Saturday",
      time: "10:00 AM – 4:00 PM",
      duration: "6 Hours",
      eventMode: ["Online"],
      instructor: "Faizan Ansari",
      seatsLeft: 18,
      totalSeats: 30,
      price: "₹2,499",
      originalPrice: "₹3,999",
      outcomes: [
        "Write clean Python code for data manipulation using pandas",
        "Perform statistical analysis and array operations with NumPy",
        "Create publication-ready visualisations with Matplotlib and Seaborn",
        "Explore, clean, and prepare real-world datasets end-to-end",
        "Complete a portfolio-worthy EDA project on a real dataset",
      ],
      curriculum: [
        {
          time: "10:00 – 11:00",
          title: "Python & Jupyter Fundamentals",
          desc: "Data types, functions, control flow, and Jupyter notebook setup",
        },
        {
          time: "11:00 – 12:00",
          title: "NumPy & pandas Deep Dive",
          desc: "Arrays, DataFrames, indexing, merging, groupby, and aggregations",
        },
        {
          time: "12:00 – 12:30",
          title: "Data Cleaning in Practice",
          desc: "Handle missing values, remove duplicates, and fix data types",
        },
        {
          time: "12:30 – 14:00",
          title: "Visualisation with Matplotlib & Seaborn",
          desc: "Bar, line, scatter, heatmaps, pairplots, and correlation matrices",
        },
        {
          time: "14:00 – 16:00",
          title: "Capstone: End-to-End EDA Project",
          desc: "Analyse and visualise a real-world dataset and present key insights",
        },
      ],
      whoIsItFor: [
        "Analysts who want to go beyond Excel and SQL into Python",
        "Freshers targeting data analyst or junior data scientist roles",
        "Anyone who started Python but never got past the basics",
        "Professionals who work with large datasets and need automation",
      ],
    },
    {
      id: 1005,
      slug: "ml-fundamentals",
      image:
        "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80&auto=format&fit=crop",
      category: "Data Science & AI",
      categoryColor: "#0d9488",
      level: "Advanced",
      title: "ML Fundamentals with Python",
      desc: "Supervised & unsupervised learning, model evaluation, and scikit-learn pipelines. Build real predictive models.",
      tags: [
        "Machine Learning",
        "Scikit-learn",
        "Regression",
        "Classification",
      ],
      date: "April 26, Saturday",
      time: "10:00 AM – 4:00 PM",
      duration: "6 Hours",
      eventMode: ["Online"],
      instructor: "Faizan Ansari",
      seatsLeft: 3,
      totalSeats: 20,
      price: "₹3,499",
      originalPrice: "₹4,999",
      outcomes: [
        "Understand the machine learning workflow end-to-end",
        "Implement regression and classification models with scikit-learn",
        "Evaluate models using accuracy, precision, recall, and ROC-AUC",
        "Handle feature engineering, scaling, and train-test splits correctly",
        "Build a complete predictive model on a real dataset from scratch",
      ],
      curriculum: [
        {
          time: "10:00 – 10:45",
          title: "ML Concepts & the Scikit-learn API",
          desc: "Supervised vs unsupervised learning, the fit/predict pattern, pipelines",
        },
        {
          time: "10:45 – 11:45",
          title: "Regression Models",
          desc: "Linear regression, Ridge, Lasso - theory, implementation, and tuning",
        },
        {
          time: "11:45 – 12:45",
          title: "Classification Models",
          desc: "Logistic regression, decision trees, random forests, and SVM",
        },
        {
          time: "12:45 – 13:30",
          title: "Model Evaluation & Hyperparameter Tuning",
          desc: "Confusion matrix, cross-validation, GridSearchCV, and ROC-AUC",
        },
        {
          time: "13:30 – 16:00",
          title: "Capstone: Build a Real Predictive Model",
          desc: "Full pipeline from raw data to a working, evaluated ML model",
        },
      ],
      whoIsItFor: [
        "Python users who are ready to step into machine learning",
        "Data analysts who want to transition into data science roles",
        "Students preparing for DS and ML technical interviews",
        "Anyone curious about how AI systems actually work under the hood",
      ],
    },
    {
      id: 1006,
      slug: "genai-for-business",
      image:
        "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80&auto=format&fit=crop",
      category: "Generative AI",
      categoryColor: "#7c3aed",
      level: "Beginner",
      title: "GenAI for Business Professionals",
      desc: "Use ChatGPT, Copilot, and AI tools to automate reports, analyse data, and make smarter decisions - no coding needed.",
      tags: ["ChatGPT", "Copilot", "Prompt Engineering", "AI Tools"],
      date: "May 3, Saturday",
      time: "11:00 AM – 2:00 PM",
      duration: "3 Hours",
      eventMode: ["Online", "Offline"],
      instructor: "Waseem Ahmad",
      seatsLeft: 20,
      totalSeats: 40,
      price: "₹999",
      originalPrice: "₹1,499",
      outcomes: [
        "Use ChatGPT and Copilot to automate reports, emails, and presentations",
        "Write effective prompts that produce reliable, high-quality AI outputs",
        "Analyse data and generate insights with AI - no coding required",
        "Build AI-powered workflows to 10x your daily productivity",
        "Understand AI limitations and avoid common costly mistakes",
      ],
      curriculum: [
        {
          time: "11:00 – 11:40",
          title: "Introduction to Generative AI",
          desc: "How LLMs work, ChatGPT vs Gemini vs Copilot - the real differences",
        },
        {
          time: "11:40 – 12:10",
          title: "Prompt Engineering Essentials",
          desc: "Zero-shot, few-shot, chain-of-thought - write prompts that actually work",
        },
        {
          time: "12:10 – 12:40",
          title: "AI for Data & Business Reporting",
          desc: "Analyse spreadsheets, generate charts, and summarise long reports with AI",
        },
        {
          time: "12:40 – 13:10",
          title: "Automating Business Workflows",
          desc: "Emails, proposals, meeting notes, SOPs - automate the boring parts",
        },
        {
          time: "13:10 – 14:00",
          title: "Hands-on Practice & Real Use Cases",
          desc: "Live demos on real business scenarios and personalised Q&A",
        },
      ],
      whoIsItFor: [
        "Business professionals who want to work smarter with AI tools",
        "Managers and team leads looking to boost their team's productivity",
        "Non-technical professionals curious about AI's real business value",
        "Entrepreneurs and freelancers who want to automate their workflows",
      ],
    },
  ],
  previous: [
    {
      id: 2001,
      image:
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop",
      category: "Data Analytics",
      categoryColor: "#16a34a",
      title: "Data Warehousing for Data Engineering",
      date: "November 15, 2024",
      duration: "3 Hours",
      eventMode: ["Offline", "Online"],
      attendees: 28,
      rating: 4.9,
    },
    {
      id: 2002,
      image:
        "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
      category: "Data Science & AI",
      categoryColor: "#0d9488",
      title: "Introduction to Machine Learning",
      date: "December 21, 2024",
      duration: "6 Hours",
      eventMode: ["Online"],
      attendees: 34,
      rating: 4.8,
    },
    {
      id: 2003,
      image:
        "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80&auto=format&fit=crop",
      category: "Data Visualization",
      categoryColor: "#f97316",
      title: "Tableau for Business Intelligence",
      date: "January 18, 2025",
      duration: "3 Hours",
      eventMode: ["Offline", "Online"],
      attendees: 22,
      rating: 5.0,
    },
    {
      id: 2004,
      image:
        "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80&auto=format&fit=crop",
      category: "Data Analytics",
      categoryColor: "#16a34a",
      title: "Advanced SQL & Query Optimization",
      date: "February 8, 2025",
      duration: "3 Hours",
      eventMode: ["Online"],
      attendees: 31,
      rating: 4.9,
    },
  ],
};

export const teamData = [
  {
    id: 1,
    name: "Waseem Ahmad",
    position: "Founder",
    profile: "WASEEM",
    image: "/assets/hobbies/dev_2.jpg",
    bio: "Founder of AnalyticShala and career analytics mentor. With years of hands-on experience in data, Waseem built AnalyticShala to make industry-grade data education accessible to everyone - not just those who can afford premium institutes.",
    social: [
      {
        href: "https://www.linkedin.com/in/waseem-ahmad-59386617a/",
        iconClass: "fab fa-linkedin-in",
      },
    ],
  },

  {
    id: 2,
    name: "Faizan Ansari",
    position: "Data Science & AI Trainer, Career Coach",
    college: "ISB Alumnus",
    profile: "FAIZAN",
    image: "/assets/hobbies/dev_2.jpg",
    bio: "ISB alumnus and Data Science & AI Trainer with 8+ years of industry experience. Has trained 500+ professionals at Fortune 500 companies and mentored dozens of candidates into top data roles at Accenture, Deloitte, and more.",
    social: [
      {
        href: "https://www.linkedin.com/in/faizan-ansari-8989ab125",
        iconClass: "fab fa-linkedin-in",
      },
    ],
  },
  {
    id: 3,
    name: "Aishvarya Joshi",
    position: "Business Development Manager",
    profile: "AISHVARYA",
    image: "/assets/hobbies/dev_1.jpg",
    bio: "Drives growth and partnerships at AnalyticShala, connecting aspiring data professionals with the right programs and career opportunities.",
    social: [],
  },
  {
    id: 4,
    name: "Tanfiz Hussain",
    position: "Business Development Manager",
    profile: "TANFIZ",
    image: "/assets/hobbies/dev_3.jpg",
    bio: "Helps learners navigate the AnalyticShala ecosystem - from program selection to placement support - ensuring every student gets the most out of their learning journey.",
    social: [],
  },
  {
    id: 5,
    name: "Riyaz Akhtar",
    position: "Web Developer, Trainer",
    profile: "RIYAZ",
    image: "/assets/hobbies/dev_3.jpg",
    social: [
      {
        href: "https://github.com/SonuAkhtar",
        iconClass: "fab fa-github",
      },
      {
        href: "https://www.linkedin.com/in/riyaz-akhtar-03bb59129/",
        iconClass: "fab fa-linkedin-in",
      },
    ],
  },
];

export const contactData = [
  {
    id: 0,
    icon: "/assets/contact/call.gif",
    name: "Call",
    info: "+91-88826 41988",
    href: "tel:+918882641988",
    alt: "call",
  },
  {
    id: 1,
    icon: "/assets/contact/email.gif",
    name: "Email",
    info: "team@analyticshala.in",
    href: "mailto:team@analyticshala.in",
    alt: "email",
  },
  {
    id: 2,
    icon: "/assets/contact/location.gif",
    name: "Location",
    info: "Gurgaon - India",
    alt: "location",
  },
];

export const testimonyData = [
  {
    id: 1,
    image: "/assets/testimony/boy.jpg",
    review:
      "I had a highly positive experience completing the SQL course with AnalyticShala. The instructor is very knowledgeable, clear and responsive, ensuring an engaging and effective learning experience. I look forward to enrolling in future courses.",
    name: "Sameer",
    position: "Data Analyst @Infosys",
  },
  {
    id: 2,
    image: "/assets/testimony/girl.webp",
    review:
      "I recently took Data Analytics using Python classes with AnalyticShala, and my experience was exceptional. The course provided a deep and practical understanding of the subject, with the instructor's knowledge and clear teaching style making complex concepts easy to grasp.",
    name: "Neha",
    position: "Manager @genpact",
  },
  {
    id: 3,
    image: "/assets/testimony/boy.jpg",
    review:
      "I received excellent support from AnalyticShala in my Analytics career. The support was helpful and responsive, with clear explanations throughout. The online format allowed me to learn at my own pace and complete assignments easily. The course content was concise.",
    name: "Tabjeel",
    position: "Data Analyst @Wipro",
  },
  {
    id: 4,
    image: "/assets/testimony/girl.webp",
    review:
      "Thank you AnalyticShala, for providing an outstanding learning experience. The trainer's enthusiasm and passion for Data Science and AI made complex concepts easy to understand, while keeping the sessions engaging and enjoyable.",
    name: "Tavleen",
    position: "Business Analyst @accenture",
  },
];

export const coursesData = [
  {
    id: 1,
    title: "Generative AI Development",
    category: "Generative AI",
    icon: "fas fa-robot",
    accent: "#7c3aed",
    level: "Intermediate",
    duration: "3–4 Months",
    desc: "Build real-world AI applications with LLMs, LangChain, and modern GenAI tools. Designed for developers ready to go beyond the basics.",
    chapters: [
      "Python",
      "LLMs",
      "LangChain",
      "Prompt Engineering",
      "OpenAI API",
      "RAG",
    ],
  },
  {
    id: 2,
    title: "Data Analytics & Visualisation",
    category: "Data Analytics",
    icon: "fas fa-chart-bar",
    accent: "#16a34a",
    level: "Beginner",
    duration: "2–3 Months",
    badge: "Most Popular",
    desc: "Master the complete analytics stack - from raw data to executive dashboards. The fastest route to a data analyst role.",
    chapters: [
      "Advanced Excel",
      "SQL",
      "Power BI",
      "Tableau",
      "Principles of Visualisation",
    ],
  },
  {
    id: 3,
    title: "Data Analytics with Python",
    category: "Data Analytics",
    icon: "fas fa-python",
    accent: "#0d9488",
    level: "Intermediate",
    duration: "3 Months",
    desc: "Go beyond Excel and SQL. Use Python to clean, analyse, and visualise data at scale with industry tools.",
    chapters: ["SQL", "Python", "Pandas", "NumPy", "Seaborn", "Matplotlib"],
  },
  {
    id: 4,
    title: "Web Development",
    category: "Web Development",
    icon: "fas fa-code",
    accent: "#f97316",
    level: "Beginner",
    duration: "4–5 Months",
    desc: "Build production-ready web apps from scratch. Learn modern frontend and full-stack development with React and Next.js.",
    chapters: ["HTML", "CSS", "JavaScript", "ReactJS", "NextJS", "NodeJS"],
  },
  {
    id: 5,
    title: "Data Science & AI for Leaders",
    category: "Data Science",
    icon: "fas fa-brain",
    accent: "#ec4899",
    level: "Advanced",
    duration: "Coming Soon",
    badge: "New",
    desc: "Designed for managers and senior professionals. Understand AI strategy, model evaluation, and data-driven decision making at scale.",
    chapters: ["ML Strategy", "Model Evaluation", "AI Ethics", "Case Studies"],
  },
];

export const questionsData = [
  {
    id: 1,
    question:
      "Can I join these classes even if I am from a non-technical background with no former experience in programming?",
    answer:
      "Yes, absolutely. AnalyticShala is open to everyone, regardless of their technical background. We use straightforward teaching methods to help students understand analytics easily and develop a strong interest in the subject. Our aim is to make analytics accessible and enjoyable for all participants, regardless of their initial knowledge level.",
  },
  {
    id: 2,
    question: "What if I miss a class?",
    answer:
      "All live sessions are recorded and shared with enrolled students within 24 hours, so you never miss out on course content. Comprehensive notes are also provided for every session. We do recommend attending live classes for the interactive Q&A, but life happens - the recordings have you covered.",
  },
  {
    id: 3,
    question: "Can I be assured of a guaranteed placement?",
    answer:
      "At AnalyticShala, we aim to make you self-sufficient. We provide all the necessary study material, and try to make the student confident enough to crack interviews of all sorts.",
  },
  {
    id: 4,
    question:
      "Will I be able to manage and understand these classes alongside my office work?",
    answer:
      "Our classes are held on weekends only. Apart from this, if you take out just an hour everyday for revision, you should be good to go.",
  },
];

export const scrollCardsData = [
  {
    id: 1,
    title: "Live Weekend Batches",
    info: "Join live classes every weekend led by working data professionals - not just teachers. Get real-time feedback, doubt resolution, and a structured learning environment that fits your schedule.",
  },
  {
    id: 2,
    title: "Recorded Sessions + Notes",
    info: "Missed a class? No problem. Every session is recorded and paired with comprehensive notes so you can revisit complex topics at your own pace and never fall behind.",
  },
  {
    id: 3,
    title: "Interview Prep & Mock Tests",
    info: "We simulate real data analyst and data science interviews - from SQL rounds and case studies to Python coding challenges. Graduate ready to ace your first interview.",
  },
  {
    id: 4,
    title: "Real-World Capstone Projects",
    info: "Build a portfolio employers will notice. Work on actual datasets from e-commerce, finance, and healthcare domains - the kind of projects you can demo in your next job interview.",
  },
  {
    id: 5,
    title: "Career Support & Alumni Network",
    info: "From resume reviews to LinkedIn profile audits and introductions to hiring partners - our career team stays with you until you land the role, and beyond.",
  },
];

export const courseListData = [
  {
    id: "ai",
    slug: "artificial-intelligence",
    icon: "fas fa-brain",
    badge: "Trending",
    badgeColor: "badge-orange",
    title: "Artificial Intelligence",
    subtitle: "From Fundamentals to Applied AI",
    level: "Beginner → Advanced",
    duration: "8 weeks",
    modules: 12,
    color: "card-green",
    description:
      "Master the foundations of AI including machine learning, neural networks, and real-world AI deployment. Build intelligent systems that solve actual business problems.",
    skills: [
      "Machine Learning",
      "Neural Networks",
      "TensorFlow / PyTorch",
      "Model Deployment",
      "Computer Vision",
      "NLP Basics",
    ],
    outcomes: [
      "Build and train ML models from scratch",
      "Implement neural networks for classification & regression",
      "Deploy AI models to production environments",
      "Apply AI to solve real business problems",
    ],
  },
  {
    id: "agentic",
    slug: "agentic-ai",
    icon: "fas fa-robot",
    badge: "New",
    badgeColor: "badge-purple",
    title: "Agentic AI",
    subtitle: "Build Autonomous AI Agents",
    level: "Intermediate → Advanced",
    duration: "6 weeks",
    modules: 10,
    color: "card-purple",
    description:
      "Design, build, and deploy autonomous AI agents using LangChain, LangGraph, AutoGen, and modern agentic frameworks. Go beyond chatbots.",
    skills: [
      "LangChain & LangGraph",
      "AutoGen / CrewAI",
      "Tool Use & Function Calling",
      "Multi-Agent Systems",
      "ReAct & CoT Prompting",
      "Memory & Planning",
    ],
    outcomes: [
      "Design multi-step agentic workflows",
      "Build agents that use tools and APIs autonomously",
      "Create multi-agent collaboration pipelines",
      "Deploy production-ready AI agents",
    ],
  },
  {
    id: "rag",
    slug: "rag-systems",
    icon: "fas fa-layer-group",
    badge: "Hot",
    badgeColor: "badge-red",
    title: "RAG Systems",
    subtitle: "Retrieval-Augmented Generation",
    level: "Intermediate",
    duration: "5 weeks",
    modules: 8,
    color: "card-teal",
    description:
      "Build powerful RAG pipelines using vector databases, embeddings, and LLMs. Make AI systems smarter with your own private data.",
    skills: [
      "Vector Databases",
      "Text Embeddings",
      "Pinecone / Chroma / FAISS",
      "OpenAI & Anthropic APIs",
      "Chunking Strategies",
      "Hybrid Search",
    ],
    outcomes: [
      "Build end-to-end RAG pipelines",
      "Optimize retrieval accuracy and relevance",
      "Create custom knowledge base chatbots",
      "Evaluate and improve RAG performance",
    ],
  },
  {
    id: "analytics",
    slug: "data-analytics",
    icon: "fas fa-chart-bar",
    badge: "Popular",
    badgeColor: "badge-green",
    title: "Data Analytics",
    subtitle: "Turn Data into Business Insights",
    level: "Beginner → Intermediate",
    duration: "7 weeks",
    modules: 11,
    color: "card-blue",
    description:
      "Collect, clean, analyze, and visualize data to drive business decisions. Learn the tools and thinking used by top analysts worldwide.",
    skills: [
      "Python & Pandas",
      "Tableau / Power BI",
      "Statistical Analysis",
      "Data Visualization",
      "KPI Dashboards",
      "A/B Testing",
    ],
    outcomes: [
      "Build interactive dashboards and reports",
      "Perform exploratory data analysis (EDA)",
      "Identify trends, patterns, and anomalies",
      "Present data insights to stakeholders",
    ],
  },
  {
    id: "datascience",
    slug: "data-science",
    icon: "fas fa-flask",
    badge: null,
    badgeColor: "",
    title: "Data Science",
    subtitle: "End-to-End Data Science Projects",
    level: "Intermediate → Advanced",
    duration: "10 weeks",
    modules: 14,
    color: "card-green",
    description:
      "Master the full data science lifecycle - from problem framing and data collection to modeling, evaluation, and deployment in production.",
    skills: [
      "Python & Scikit-learn",
      "Feature Engineering",
      "Model Evaluation",
      "Time Series Analysis",
      "ML Pipelines",
      "MLOps Basics",
    ],
    outcomes: [
      "Execute complete data science projects end-to-end",
      "Build predictive and classification models",
      "Handle real-world messy datasets confidently",
      "Deploy models as REST APIs",
    ],
  },
  {
    id: "sql",
    slug: "sql-for-data-analysis",
    icon: "fas fa-server",
    badge: "Essential",
    badgeColor: "badge-blue",
    title: "SQL Mastery",
    subtitle: "From Queries to Query Optimization",
    level: "Beginner → Advanced",
    duration: "5 weeks",
    modules: 9,
    color: "card-teal",
    description:
      "Go from basic SELECT statements to advanced window functions, query optimization, and database design with rigorous hands-on practice.",
    skills: [
      "SELECT, JOIN, GROUP BY",
      "Window Functions",
      "CTEs & Subqueries",
      "Index & Query Optimization",
      "Database Design & Normalization",
      "PostgreSQL / MySQL",
    ],
    outcomes: [
      "Write complex multi-table queries with confidence",
      "Optimize slow queries for large datasets",
      "Design clean, normalized database schemas",
      "Analyze large datasets entirely in SQL",
    ],
  },
  {
    id: "excel",
    slug: "advanced-excel",
    icon: "fas fa-table",
    badge: null,
    badgeColor: "",
    title: "Advanced Excel",
    subtitle: "Power Tools for Data Professionals",
    level: "Intermediate → Advanced",
    duration: "4 weeks",
    modules: 8,
    color: "card-orange",
    description:
      "Unlock Excel's full potential - from advanced formulas and pivot tables to Power Query automation, dynamic dashboards, and VBA macros.",
    skills: [
      "XLOOKUP / INDEX-MATCH",
      "Pivot Tables & Charts",
      "Power Query (M Language)",
      "Dynamic Arrays & LAMBDA",
      "VBA & Macro Automation",
      "Executive Dashboard Design",
    ],
    outcomes: [
      "Automate repetitive tasks with VBA macros",
      "Build executive-ready interactive dashboards",
      "Transform and clean data with Power Query",
      "Master advanced formulas and dynamic arrays",
    ],
  },
];

export const courseRegData = {
  ai: {
    regFee: "₹500",
    price: "₹12,999",
    originalPrice: "₹19,999",
    emi: "₹1,083/mo",
    nextBatch: "April 5, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "8 weeks of live weekend sessions",
      "Recorded lectures for all modules",
      "12 hands-on projects & case studies",
      "Doubt resolution support",
      "Course completion certificate",
      "Lifetime community access",
    ],
    whoIsItFor: [
      "Developers and engineers looking to add AI to their skillset",
      "Data professionals transitioning to AI/ML roles",
      "Freshers aiming for AI/ML engineer positions",
      "Tech enthusiasts who want to build and deploy real AI systems",
    ],
    curriculum: [
      {
        week: "Week 1–2",
        title: "ML Foundations & Python for AI",
        desc: "NumPy, pandas, scikit-learn, train/test splits, and your first ML model",
      },
      {
        week: "Week 3–4",
        title: "Neural Networks & Deep Learning",
        desc: "Perceptrons, backprop, CNNs, RNNs - built with TensorFlow & PyTorch",
      },
      {
        week: "Week 5–6",
        title: "Computer Vision & NLP Basics",
        desc: "Image classification, object detection, text classification, and embeddings",
      },
      {
        week: "Week 7",
        title: "Model Evaluation & Tuning",
        desc: "Cross-validation, hyperparameter tuning, metrics, and avoiding overfitting",
      },
      {
        week: "Week 8",
        title: "Deployment & Capstone Project",
        desc: "Deploy your AI model as a REST API; build and present a full end-to-end project",
      },
    ],
  },
  agentic: {
    regFee: "₹500",
    price: "₹14,999",
    originalPrice: "₹22,999",
    emi: "₹1,250/mo",
    nextBatch: "April 12, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "6 weeks of live weekend sessions",
      "Recorded sessions & code notebooks",
      "10 agentic AI mini-projects",
      "LangChain & LangGraph starter kits",
      "Course completion certificate",
      "Access to private Discord community",
    ],
    whoIsItFor: [
      "AI/ML engineers who want to go beyond chatbots",
      "Developers already familiar with Python and LLMs",
      "Product managers exploring agentic AI architectures",
      "Builders who want to create autonomous AI workflows",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "LLM APIs & Prompt Engineering",
        desc: "OpenAI, Anthropic APIs; zero-shot, few-shot, chain-of-thought techniques",
      },
      {
        week: "Week 2",
        title: "LangChain Fundamentals",
        desc: "Chains, memory, agents, tools, and the LangChain Expression Language (LCEL)",
      },
      {
        week: "Week 3",
        title: "LangGraph & Stateful Agents",
        desc: "Build stateful, multi-step agentic workflows with LangGraph graphs",
      },
      {
        week: "Week 4",
        title: "Tool Use & Function Calling",
        desc: "Give your agents real tools - web search, code execution, APIs, and more",
      },
      {
        week: "Week 5",
        title: "Multi-Agent Systems",
        desc: "AutoGen, CrewAI - build teams of agents that collaborate on complex tasks",
      },
      {
        week: "Week 6",
        title: "Production & Capstone",
        desc: "Deploy your agent, add monitoring, and present your autonomous AI system",
      },
    ],
  },
  rag: {
    regFee: "₹500",
    price: "₹9,999",
    originalPrice: "₹14,999",
    emi: "₹834/mo",
    nextBatch: "April 19, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "5 weeks of live weekend sessions",
      "Recorded sessions & Jupyter notebooks",
      "8 RAG pipeline projects",
      "Vector DB starter kits (Pinecone, Chroma)",
      "Course completion certificate",
      "Lifetime community access",
    ],
    whoIsItFor: [
      "AI engineers who want to build knowledge-base chatbots",
      "Developers integrating private data into LLM applications",
      "Data engineers building production-grade AI pipelines",
      "Anyone who wants to go beyond generic AI responses",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "LLMs, Embeddings & Vector Search",
        desc: "How LLMs work, text embeddings, cosine similarity, and vector indices",
      },
      {
        week: "Week 2",
        title: "Vector Databases",
        desc: "Pinecone, Chroma, FAISS - setup, indexing, and query optimization",
      },
      {
        week: "Week 3",
        title: "RAG Pipeline Architecture",
        desc: "Document loading, chunking strategies, retrieval, and augmented generation",
      },
      {
        week: "Week 4",
        title: "Advanced RAG Techniques",
        desc: "Hybrid search, re-ranking, HyDE, and improving retrieval accuracy",
      },
      {
        week: "Week 5",
        title: "Evaluation & Capstone",
        desc: "Evaluate your RAG pipeline with RAGAS; build and deploy a full RAG chatbot",
      },
    ],
  },
  analytics: {
    regFee: "₹500",
    price: "₹10,999",
    originalPrice: "₹16,999",
    emi: "₹917/mo",
    nextBatch: "April 5, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "7 weeks of live weekend sessions",
      "Recorded sessions & datasets",
      "11 real-world analytics projects",
      "Power BI & Tableau starter templates",
      "Course completion certificate",
      "Career placement support",
    ],
    whoIsItFor: [
      "Freshers targeting data analyst roles at top companies",
      "Excel users who want to level up to Python and BI tools",
      "Business professionals who work with data daily",
      "Students preparing for analytics and data roles",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "Excel & Data Fundamentals",
        desc: "Advanced Excel formulas, pivot tables, and dashboarding",
      },
      {
        week: "Week 2",
        title: "SQL for Analytics",
        desc: "JOINs, window functions, CTEs, and business query patterns",
      },
      {
        week: "Week 3–4",
        title: "Python for Data Analysis",
        desc: "pandas, NumPy, EDA, and data cleaning with real datasets",
      },
      {
        week: "Week 5",
        title: "Statistical Analysis",
        desc: "Descriptive stats, hypothesis testing, A/B testing, and distributions",
      },
      {
        week: "Week 6",
        title: "Data Visualization",
        desc: "Tableau and Power BI - build interactive, executive-ready dashboards",
      },
      {
        week: "Week 7",
        title: "Capstone Project",
        desc: "End-to-end analytics project: collect, clean, analyse, and present insights",
      },
    ],
  },
  datascience: {
    regFee: "₹500",
    price: "₹15,999",
    originalPrice: "₹24,999",
    emi: "₹1,334/mo",
    nextBatch: "May 3, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "10 weeks of live weekend sessions",
      "Recorded lectures & Jupyter notebooks",
      "14 end-to-end DS projects",
      "ML model deployment guide",
      "Course completion certificate",
      "1-on-1 career mentorship session",
    ],
    whoIsItFor: [
      "Python developers transitioning into data science",
      "Data analysts looking to add ML to their toolkit",
      "Students targeting data scientist and ML engineer roles",
      "Professionals who want to build and deploy predictive models",
    ],
    curriculum: [
      {
        week: "Week 1–2",
        title: "Python, EDA & Feature Engineering",
        desc: "Advanced pandas, missing value treatment, outlier handling, feature creation",
      },
      {
        week: "Week 3–4",
        title: "Supervised ML Models",
        desc: "Linear & logistic regression, decision trees, random forests, gradient boosting",
      },
      {
        week: "Week 5",
        title: "Model Evaluation & Tuning",
        desc: "Cross-validation, GridSearchCV, ROC-AUC, precision-recall, learning curves",
      },
      {
        week: "Week 6–7",
        title: "Unsupervised Learning & NLP Basics",
        desc: "Clustering, dimensionality reduction, text vectorization, sentiment analysis",
      },
      {
        week: "Week 8–9",
        title: "Time Series & ML Pipelines",
        desc: "ARIMA, Prophet, sklearn pipelines, and MLOps fundamentals",
      },
      {
        week: "Week 10",
        title: "Deployment & Capstone",
        desc: "Flask/FastAPI REST APIs, Docker basics, and full DS project presentation",
      },
    ],
  },
  sql: {
    regFee: "₹500",
    price: "₹6,999",
    originalPrice: "₹10,999",
    emi: "₹584/mo",
    nextBatch: "April 12, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "5 weeks of live weekend sessions",
      "Recorded sessions & query workbooks",
      "9 real-world SQL projects",
      "PostgreSQL & MySQL practice datasets",
      "Course completion certificate",
      "SQL interview question bank (200+)",
    ],
    whoIsItFor: [
      "Beginners who have never written a SQL query before",
      "Analysts who want to write faster, more complex queries",
      "Developers who want to understand database design",
      "Anyone preparing for data analyst or BI engineer interviews",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "SQL Foundations",
        desc: "SELECT, WHERE, ORDER BY, LIMIT, aggregate functions, and GROUP BY",
      },
      {
        week: "Week 2",
        title: "JOINs & Relationships",
        desc: "INNER, LEFT, RIGHT, FULL OUTER, SELF JOINs, and relationship design",
      },
      {
        week: "Week 3",
        title: "CTEs, Subqueries & CASE",
        desc: "WITH clauses, nested queries, conditional logic, and UNION operations",
      },
      {
        week: "Week 4",
        title: "Window Functions & Analytics",
        desc: "ROW_NUMBER, RANK, LEAD, LAG, running totals, and moving averages",
      },
      {
        week: "Week 5",
        title: "Query Optimization & Capstone",
        desc: "Index basics, EXPLAIN plans, query rewrites, and interview SQL challenges",
      },
    ],
  },
  excel: {
    regFee: "₹500",
    price: "₹4,999",
    originalPrice: "₹7,999",
    emi: "₹417/mo",
    nextBatch: "April 5, 2026",
    batchType: "Weekend Batch",
    instructor: "Faizan Ansari",
    includes: [
      "4 weeks of live weekend sessions",
      "Recorded sessions & Excel workbooks",
      "8 dashboard & automation projects",
      "VBA macro starter kit",
      "Course completion certificate",
      "Excel interview question bank",
    ],
    whoIsItFor: [
      "Working professionals who use Excel but haven't mastered it",
      "Freshers who want an analyst-ready Excel skillset",
      "Finance, operations, and marketing professionals",
      "Anyone who wants to automate and visualize data in Excel",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "Advanced Formulas & Lookup Functions",
        desc: "XLOOKUP, INDEX-MATCH, dynamic arrays, LAMBDA, and formula auditing",
      },
      {
        week: "Week 2",
        title: "Pivot Tables, Charts & Dashboards",
        desc: "Pivot tables, slicers, dynamic charts, and interactive dashboard design",
      },
      {
        week: "Week 3",
        title: "Power Query & Data Transformation",
        desc: "ETL with Power Query (M Language), merging tables, and data shaping",
      },
      {
        week: "Week 4",
        title: "VBA Macros & Capstone",
        desc: "Automate tasks with VBA, build a real business automation, and final project",
      },
    ],
  },
};

export const aboutUsText =
  "At AnalyticShala, we empower learners to thrive in today’s data-driven and AI-powered world. We offer industry-focused courses in Data Analytics, Data Science, Artificial Intelligence, Generative AI, Data Visualization, and Web Development, designed to turn concepts into real-world skills. Our programs blend hands-on learning, practical projects, and real-life use cases, helping you build strong foundations and stay ahead in a rapidly evolving tech landscape.";
