name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: deploye build to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.analyticshala.in
          username: u500602524.deployanalyticshala
          password: Analyticshala@1234
          local-dir: build
          server-dir: public_html/
